#!/usr/bin/env python3

import sys
import os

if os.geteuid() != 0:
    sys.exit("You need root privileges to run this script.")

if len(sys.argv) != 2:
    print("Usage: sudo warper <on/off/status>")
    sys.exit()

username = os.getlogin()
home = f"/home/{username}"
dir_path = os.path.dirname(os.path.realpath(__file__))
option = sys.argv[1]

resolv = '/etc/resolv.conf'
copied_location = f'{home}/.config/warper/resolv_copy/resolv.conf'

def copy_current():
    os.system(f"mkdir -p {home}/.config/warper/resolv_copy")
    os.system(f"cp -i /etc/resolv.conf {copied_location}")

def status():
    with open(resolv) as read_resolv:
        resolvcontent = read_resolv.read()
        read_resolv.close()
    check_resolv = "nameserver 1.0.0.1\nnameserver 1.1.1.1\n"
    if check_resolv == resolvcontent:
        print("\033[1mCurrent status is: \033[32;5mON")
    else:
        print("\033[1mCurrent status is: \033[91;5mOFF")
def open_warp():
    with open(resolv, "w") as resolvconf:
        resolvconf.write("nameserver 1.0.0.1\nnameserver 1.1.1.1\n")
        resolvconf.close()

def close_warp():
    os.system("rm /etc/resolv.conf")
    os.system(f"cp {home}/.config/warper/resolv_copy/resolv.conf /etc/resolv.conf")


if option.lower() == "on":
    copy_current()
    open_warp()
elif option.lower() == "off":
    close_warp()
    os.system(f"rm {copied_location}")
elif option.lower() == "status":
    status()
else:
    print("Usage: warper <on/off/status>")
